"""triage runs

Revision ID: 2a626bf37d68
Revises: d3a91f0c77b1
Create Date: 2026-09-13 22:54:43.835543
"""
from alembic import op
import sqlalchemy as sa


revision = '2a626bf37d68'
down_revision = 'd3a91f0c77b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot', sa.String(length=40), nullable=False),
    sa.Column('artifact_ref', sa.String(length=200), nullable=False),
    sa.Column('hub_id', sa.String(length=32), nullable=True),
    sa.Column('event_code', sa.String(length=40), nullable=True),
    sa.Column('procedure_id', sa.String(length=40), nullable=False),
    sa.Column('procedure_revision', sa.String(length=20), nullable=False),
    sa.Column('procedure_verification', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('disposition', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('deciding_step', sa.String(length=20), nullable=True),
    sa.Column('citation', sa.String(length=80), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('escalate_to', sa.String(length=80), nullable=True),
    sa.Column('checks_run', sa.Integer(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('actual_cause', sa.String(length=40), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['capture_draft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_run_actual_cause'), 'triage_run', ['actual_cause'], unique=False)
    op.create_index(op.f('ix_triage_run_artifact_ref'), 'triage_run', ['artifact_ref'], unique=True)
    op.create_index(op.f('ix_triage_run_bot'), 'triage_run', ['bot'], unique=False)
    op.create_index(op.f('ix_triage_run_correct'), 'triage_run', ['correct'], unique=False)
    op.create_index(op.f('ix_triage_run_disposition'), 'triage_run', ['disposition'], unique=False)
    op.create_index(op.f('ix_triage_run_draft_id'), 'triage_run', ['draft_id'], unique=False)
    op.create_index(op.f('ix_triage_run_event_code'), 'triage_run', ['event_code'], unique=False)
    op.create_index(op.f('ix_triage_run_hub_id'), 'triage_run', ['hub_id'], unique=False)
    op.create_index(op.f('ix_triage_run_outcome'), 'triage_run', ['outcome'], unique=False)
    op.create_table('triage_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.String(length=20), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('satisfied', sa.String(length=60), nullable=True),
    sa.Column('outcome', sa.String(length=40), nullable=True),
    sa.Column('goto', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('probes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['triage_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_step_run_id'), 'triage_step', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_step_run_id'), table_name='triage_step')
    op.drop_table('triage_step')
    op.drop_index(op.f('ix_triage_run_outcome'), table_name='triage_run')
    op.drop_index(op.f('ix_triage_run_hub_id'), table_name='triage_run')
    op.drop_index(op.f('ix_triage_run_event_code'), table_name='triage_run')
    op.drop_index(op.f('ix_triage_run_draft_id'), table_name='triage_run')
    op.drop_index(op.f('ix_triage_run_disposition'), table_name='triage_run')
    op.drop_index(op.f('ix_triage_run_correct'), table_name='triage_run')
    op.drop_index(op.f('ix_triage_run_bot'), table_name='triage_run')
    op.drop_index(op.f('ix_triage_run_artifact_ref'), table_name='triage_run')
    op.drop_index(op.f('ix_triage_run_actual_cause'), table_name='triage_run')
    op.drop_table('triage_run')
    # ### end Alembic commands ###
