"""registers and capture layer

Revision ID: 48632b40bbe6
Revises: 
Create Date: 2026-09-13 21:08:34.119962
"""
from alembic import op
import sqlalchemy as sa


revision = '48632b40bbe6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.String(length=40), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('workflow', sa.String(length=60), nullable=False),
    sa.Column('autonomy_level', sa.Enum('1', '2', '3', '4', '5', name='autonomy', native_enum=False), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('rule_model_version', sa.String(length=80), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('human_verdict', sa.Enum('accepted', 'edited', 'rejected', name='humanverdict', native_enum=False), nullable=True),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_action_action_id'), 'agent_action', ['action_id'], unique=True)
    op.create_index(op.f('ix_agent_action_human_verdict'), 'agent_action', ['human_verdict'], unique=False)
    op.create_index(op.f('ix_agent_action_tier'), 'agent_action', ['tier'], unique=False)
    op.create_index(op.f('ix_agent_action_timestamp'), 'agent_action', ['timestamp'], unique=False)
    op.create_index(op.f('ix_agent_action_workflow'), 'agent_action', ['workflow'], unique=False)
    op.create_table('capa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capa_id', sa.String(length=40), nullable=False),
    sa.Column('date_recommended', sa.Date(), nullable=True),
    sa.Column('date_opened', sa.Date(), nullable=True),
    sa.Column('trigger', sa.Enum('Recurrence', 'Cross-register convergence', 'Prior NC ineffective', 'Single severe NC', 'External', name='capatrigger', native_enum=False), nullable=True),
    sa.Column('raised_from', sa.JSON(), nullable=True),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('recurrence_evidence', sa.Text(), nullable=True),
    sa.Column('prior_action', sa.Text(), nullable=True),
    sa.Column('why_prior_action_did_not_hold', sa.Text(), nullable=True),
    sa.Column('product', sa.String(length=40), nullable=True),
    sa.Column('affected_scope', sa.JSON(), nullable=True),
    sa.Column('indicator_ids', sa.JSON(), nullable=True),
    sa.Column('decision', sa.Enum('Opened', 'Declined', 'Deferred', name='capadecision', native_enum=False), nullable=True),
    sa.Column('decision_rationale', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('preventive_action', sa.Text(), nullable=True),
    sa.Column('effectiveness_check', sa.Text(), nullable=True),
    sa.Column('effectiveness_verified', sa.Boolean(), nullable=True),
    sa.Column('date_closed', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('Recommended', 'Open', 'Implemented', 'Verifying', 'Closed', 'Declined', 'Deferred', name='capastatus', native_enum=False), nullable=True),
    sa.Column('row_origin', sa.Enum('Human', 'Agent (accepted)', 'Agent (edited)', name='roworigin', native_enum=False), nullable=False),
    sa.Column('captured_from', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capa_capa_id'), 'capa', ['capa_id'], unique=True)
    op.create_index(op.f('ix_capa_captured_from'), 'capa', ['captured_from'], unique=False)
    op.create_index(op.f('ix_capa_date_recommended'), 'capa', ['date_recommended'], unique=False)
    op.create_index(op.f('ix_capa_row_origin'), 'capa', ['row_origin'], unique=False)
    op.create_index(op.f('ix_capa_status'), 'capa', ['status'], unique=False)
    op.create_table('capture_draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot', sa.String(length=40), nullable=False),
    sa.Column('target_register', sa.String(length=40), nullable=False),
    sa.Column('artifact_ref', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('proposed_event_code', sa.String(length=40), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Accepted', 'Edited', 'Rejected', name='draftstatus', native_enum=False), nullable=False),
    sa.Column('committed_row_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot', 'artifact_ref', name='uq_draft_bot_artifact')
    )
    op.create_index(op.f('ix_capture_draft_artifact_ref'), 'capture_draft', ['artifact_ref'], unique=False)
    op.create_index(op.f('ix_capture_draft_bot'), 'capture_draft', ['bot'], unique=False)
    op.create_index(op.f('ix_capture_draft_proposed_event_code'), 'capture_draft', ['proposed_event_code'], unique=False)
    op.create_index(op.f('ix_capture_draft_status'), 'capture_draft', ['status'], unique=False)
    op.create_index(op.f('ix_capture_draft_target_register'), 'capture_draft', ['target_register'], unique=False)
    op.create_table('communication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comm_id', sa.String(length=40), nullable=False),
    sa.Column('email_subject', sa.Text(), nullable=True),
    sa.Column('date_of_initial_email', sa.Date(), nullable=True),
    sa.Column('date_of_last_email_sent', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('comm_type', sa.String(length=60), nullable=True),
    sa.Column('organisation_as_written', sa.String(length=200), nullable=True),
    sa.Column('client_contact', sa.String(length=120), nullable=True),
    sa.Column('contact_role', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('handled_by', sa.String(length=120), nullable=True),
    sa.Column('mailbox', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attachments', sa.Text(), nullable=True),
    sa.Column('cross_reference', sa.Text(), nullable=True),
    sa.Column('channel', sa.Enum('Email', 'Meeting', 'Phone', 'Portal', name='channel', native_enum=False), nullable=True),
    sa.Column('resolved_customer_id', sa.String(length=32), nullable=True),
    sa.Column('resolved_event_code', sa.String(length=40), nullable=True),
    sa.Column('row_origin', sa.Enum('Human', 'Agent (accepted)', 'Agent (edited)', name='roworigin', native_enum=False), nullable=False),
    sa.Column('captured_from', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_captured_from'), 'communication', ['captured_from'], unique=False)
    op.create_index(op.f('ix_communication_channel'), 'communication', ['channel'], unique=False)
    op.create_index(op.f('ix_communication_comm_id'), 'communication', ['comm_id'], unique=True)
    op.create_index(op.f('ix_communication_date_of_initial_email'), 'communication', ['date_of_initial_email'], unique=False)
    op.create_index(op.f('ix_communication_resolved_customer_id'), 'communication', ['resolved_customer_id'], unique=False)
    op.create_index(op.f('ix_communication_resolved_event_code'), 'communication', ['resolved_event_code'], unique=False)
    op.create_index(op.f('ix_communication_row_origin'), 'communication', ['row_origin'], unique=False)
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.String(length=40), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.Column('date_opened', sa.Date(), nullable=True),
    sa.Column('channel', sa.Enum('Email', 'Meeting', 'Phone', 'Portal', name='channel', native_enum=False), nullable=True),
    sa.Column('organisation_as_written', sa.String(length=200), nullable=True),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('complainant', sa.String(length=120), nullable=True),
    sa.Column('contact_role', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('product', sa.String(length=40), nullable=True),
    sa.Column('serial_number_as_written', sa.String(length=60), nullable=True),
    sa.Column('patch_lot', sa.String(length=40), nullable=True),
    sa.Column('description_as_reported', sa.Text(), nullable=True),
    sa.Column('indicator_id', sa.String(length=16), nullable=True),
    sa.Column('event_code', sa.String(length=40), nullable=True),
    sa.Column('classification_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('investigation_required', sa.Boolean(), nullable=True),
    sa.Column('investigation_summary', sa.Text(), nullable=True),
    sa.Column('vigilance_screen_required', sa.Boolean(), nullable=True),
    sa.Column('linked_comm', sa.String(length=40), nullable=True),
    sa.Column('linked_incident', sa.String(length=40), nullable=True),
    sa.Column('linked_rma', sa.String(length=40), nullable=True),
    sa.Column('linked_signal', sa.String(length=40), nullable=True),
    sa.Column('linked_nc', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('Open', 'Under investigation', 'Closed', 'Declined', name='complaintstatus', native_enum=False), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('date_closed', sa.Date(), nullable=True),
    sa.Column('closure_rationale', sa.Text(), nullable=True),
    sa.Column('customer_informed', sa.Boolean(), nullable=True),
    sa.Column('date_informed', sa.Date(), nullable=True),
    sa.Column('row_origin', sa.Enum('Human', 'Agent (accepted)', 'Agent (edited)', name='roworigin', native_enum=False), nullable=False),
    sa.Column('captured_from', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_captured_from'), 'complaint', ['captured_from'], unique=False)
    op.create_index(op.f('ix_complaint_complaint_id'), 'complaint', ['complaint_id'], unique=True)
    op.create_index(op.f('ix_complaint_customer_id'), 'complaint', ['customer_id'], unique=False)
    op.create_index(op.f('ix_complaint_date_received'), 'complaint', ['date_received'], unique=False)
    op.create_index(op.f('ix_complaint_event_code'), 'complaint', ['event_code'], unique=False)
    op.create_index(op.f('ix_complaint_indicator_id'), 'complaint', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_complaint_linked_comm'), 'complaint', ['linked_comm'], unique=False)
    op.create_index(op.f('ix_complaint_linked_incident'), 'complaint', ['linked_incident'], unique=False)
    op.create_index(op.f('ix_complaint_linked_nc'), 'complaint', ['linked_nc'], unique=False)
    op.create_index(op.f('ix_complaint_linked_rma'), 'complaint', ['linked_rma'], unique=False)
    op.create_index(op.f('ix_complaint_linked_signal'), 'complaint', ['linked_signal'], unique=False)
    op.create_index(op.f('ix_complaint_row_origin'), 'complaint', ['row_origin'], unique=False)
    op.create_index(op.f('ix_complaint_status'), 'complaint', ['status'], unique=False)
    op.create_table('completion_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot', sa.String(length=40), nullable=False),
    sa.Column('target_register', sa.String(length=40), nullable=False),
    sa.Column('target_row_key', sa.String(length=40), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('existing_value', sa.Text(), nullable=True),
    sa.Column('proposed_value', sa.Text(), nullable=False),
    sa.Column('artifact_ref', sa.String(length=200), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Accepted', 'Edited', 'Rejected', name='draftstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_register', 'target_row_key', 'field_name', name='uq_completion_target_field')
    )
    op.create_index(op.f('ix_completion_suggestion_artifact_ref'), 'completion_suggestion', ['artifact_ref'], unique=False)
    op.create_index(op.f('ix_completion_suggestion_bot'), 'completion_suggestion', ['bot'], unique=False)
    op.create_index(op.f('ix_completion_suggestion_field_name'), 'completion_suggestion', ['field_name'], unique=False)
    op.create_index(op.f('ix_completion_suggestion_status'), 'completion_suggestion', ['status'], unique=False)
    op.create_index(op.f('ix_completion_suggestion_target_register'), 'completion_suggestion', ['target_register'], unique=False)
    op.create_index(op.f('ix_completion_suggestion_target_row_key'), 'completion_suggestion', ['target_row_key'], unique=False)
    op.create_table('controlled_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.String(length=60), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('next_review_due', sa.Date(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('frequency', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controlled_document_document_id'), 'controlled_document', ['document_id'], unique=True)
    op.create_index(op.f('ix_controlled_document_status'), 'controlled_document', ['status'], unique=False)
    op.create_table('customer_organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('organisation_name', sa.String(length=200), nullable=False),
    sa.Column('legal_entity_name', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('country_region', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('timezone', sa.String(length=60), nullable=True),
    sa.Column('record_id', sa.String(length=40), nullable=True),
    sa.Column('customer_since', sa.Date(), nullable=True),
    sa.Column('units_total_stated', sa.Integer(), nullable=True),
    sa.Column('units_in_service_stated', sa.Integer(), nullable=True),
    sa.Column('wards', sa.Text(), nullable=True),
    sa.Column('primary_contact', sa.String(length=120), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=200), nullable=True),
    sa.Column('sales_channel', sa.String(length=60), nullable=True),
    sa.Column('account_owner', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_organisation_customer_id'), 'customer_organisation', ['customer_id'], unique=True)
    op.create_table('data_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.String(length=40), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=True),
    sa.Column('organisation_as_written', sa.String(length=200), nullable=True),
    sa.Column('ward', sa.String(length=40), nullable=True),
    sa.Column('bed', sa.String(length=40), nullable=True),
    sa.Column('pairing', sa.String(length=80), nullable=True),
    sa.Column('serial_number_as_written', sa.String(length=60), nullable=True),
    sa.Column('patch_lot', sa.String(length=40), nullable=True),
    sa.Column('hardware_issues', sa.Text(), nullable=True),
    sa.Column('alert_misclassifications', sa.Text(), nullable=True),
    sa.Column('patient_and_alert_issues', sa.Text(), nullable=True),
    sa.Column('software_issues', sa.Text(), nullable=True),
    sa.Column('issue_found', sa.Text(), nullable=True),
    sa.Column('checked_by', sa.String(length=120), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('resolved_customer_id', sa.String(length=32), nullable=True),
    sa.Column('resolved_hub_id', sa.String(length=32), nullable=True),
    sa.Column('resolved_event_codes', sa.String(length=200), nullable=True),
    sa.Column('row_origin', sa.Enum('Human', 'Agent (accepted)', 'Agent (edited)', name='roworigin', native_enum=False), nullable=False),
    sa.Column('captured_from', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_check_captured_from'), 'data_check', ['captured_from'], unique=False)
    op.create_index(op.f('ix_data_check_check_date'), 'data_check', ['check_date'], unique=False)
    op.create_index(op.f('ix_data_check_check_id'), 'data_check', ['check_id'], unique=True)
    op.create_index(op.f('ix_data_check_patch_lot'), 'data_check', ['patch_lot'], unique=False)
    op.create_index(op.f('ix_data_check_resolved_customer_id'), 'data_check', ['resolved_customer_id'], unique=False)
    op.create_index(op.f('ix_data_check_resolved_event_codes'), 'data_check', ['resolved_event_codes'], unique=False)
    op.create_index(op.f('ix_data_check_resolved_hub_id'), 'data_check', ['resolved_hub_id'], unique=False)
    op.create_index(op.f('ix_data_check_row_origin'), 'data_check', ['row_origin'], unique=False)
    op.create_index(op.f('ix_data_check_ward'), 'data_check', ['ward'], unique=False)
    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.String(length=40), nullable=False),
    sa.Column('pairing_id', sa.String(length=60), nullable=True),
    sa.Column('pairing_status', sa.String(length=40), nullable=True),
    sa.Column('organisation_as_written', sa.String(length=200), nullable=True),
    sa.Column('hub_id', sa.String(length=32), nullable=True),
    sa.Column('serial_number_as_written', sa.String(length=60), nullable=True),
    sa.Column('ward_id', sa.String(length=40), nullable=True),
    sa.Column('bed_id', sa.String(length=40), nullable=True),
    sa.Column('last_online', sa.DateTime(), nullable=True),
    sa.Column('offline_duration_hrs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reported_date', sa.Date(), nullable=True),
    sa.Column('incident_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('date_of_last_email_sent', sa.Date(), nullable=True),
    sa.Column('reported_by', sa.String(length=120), nullable=True),
    sa.Column('assigned_to', sa.String(length=120), nullable=True),
    sa.Column('sw_version_at_time', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('event_code', sa.String(length=40), nullable=True),
    sa.Column('source', sa.Enum('Telemetry', 'Dashboard alert', 'Ward staff', 'Email', name='incidentsource', native_enum=False), nullable=True),
    sa.Column('resolved_customer_id', sa.String(length=32), nullable=True),
    sa.Column('resolved_hub_id', sa.String(length=32), nullable=True),
    sa.Column('row_origin', sa.Enum('Human', 'Agent (accepted)', 'Agent (edited)', name='roworigin', native_enum=False), nullable=False),
    sa.Column('captured_from', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_captured_from'), 'incident', ['captured_from'], unique=False)
    op.create_index(op.f('ix_incident_event_code'), 'incident', ['event_code'], unique=False)
    op.create_index(op.f('ix_incident_hub_id'), 'incident', ['hub_id'], unique=False)
    op.create_index(op.f('ix_incident_incident_id'), 'incident', ['incident_id'], unique=True)
    op.create_index(op.f('ix_incident_pairing_id'), 'incident', ['pairing_id'], unique=False)
    op.create_index(op.f('ix_incident_reported_date'), 'incident', ['reported_date'], unique=False)
    op.create_index(op.f('ix_incident_resolved_customer_id'), 'incident', ['resolved_customer_id'], unique=False)
    op.create_index(op.f('ix_incident_resolved_hub_id'), 'incident', ['resolved_hub_id'], unique=False)
    op.create_index(op.f('ix_incident_row_origin'), 'incident', ['row_origin'], unique=False)
    op.create_index(op.f('ix_incident_sw_version_at_time'), 'incident', ['sw_version_at_time'], unique=False)
    op.create_index(op.f('ix_incident_ward_id'), 'incident', ['ward_id'], unique=False)
    op.create_table('indicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.String(length=16), nullable=False),
    sa.Column('product', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('internal_code', sa.String(length=40), nullable=False),
    sa.Column('denominator_kind', sa.Enum('unit_months', 'patches', name='denominatorkind', native_enum=False), nullable=False),
    sa.Column('baseline', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('threshold_kind', sa.Enum('ratio', 'any_increase', name='thresholdkind', native_enum=False), nullable=False),
    sa.Column('threshold_multiplier', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('escalation_as_written', sa.String(length=80), nullable=False),
    sa.Column('review_function', sa.String(length=40), nullable=False),
    sa.Column('source_document', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicator_indicator_id'), 'indicator', ['indicator_id'], unique=True)
    op.create_index(op.f('ix_indicator_internal_code'), 'indicator', ['internal_code'], unique=True)
    op.create_table('pms_review_meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.String(length=40), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=True),
    sa.Column('meeting_type', sa.String(length=60), nullable=True),
    sa.Column('attendees', sa.Text(), nullable=True),
    sa.Column('chair', sa.String(length=120), nullable=True),
    sa.Column('minutes_status', sa.String(length=40), nullable=True),
    sa.Column('items_reviewed', sa.Text(), nullable=True),
    sa.Column('actions_raised', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_review_meeting_meeting_date'), 'pms_review_meeting', ['meeting_date'], unique=False)
    op.create_index(op.f('ix_pms_review_meeting_meeting_id'), 'pms_review_meeting', ['meeting_id'], unique=True)
    op.create_table('product_nc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nc_id', sa.String(length=40), nullable=False),
    sa.Column('raised_from_signal', sa.String(length=40), nullable=True),
    sa.Column('date_raised', sa.Date(), nullable=True),
    sa.Column('product', sa.String(length=40), nullable=True),
    sa.Column('affected_scope', sa.JSON(), nullable=True),
    sa.Column('units_in_field', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('indicator_id', sa.String(length=16), nullable=True),
    sa.Column('evidence_links', sa.JSON(), nullable=True),
    sa.Column('containment', sa.Text(), nullable=True),
    sa.Column('investigation_owner', sa.String(length=120), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('disposition', sa.Text(), nullable=True),
    sa.Column('capa_considered', sa.Boolean(), nullable=True),
    sa.Column('capa_rationale', sa.Text(), nullable=True),
    sa.Column('linked_capa', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('date_closed', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_nc_date_raised'), 'product_nc', ['date_raised'], unique=False)
    op.create_index(op.f('ix_product_nc_indicator_id'), 'product_nc', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_product_nc_linked_capa'), 'product_nc', ['linked_capa'], unique=False)
    op.create_index(op.f('ix_product_nc_nc_id'), 'product_nc', ['nc_id'], unique=True)
    op.create_index(op.f('ix_product_nc_raised_from_signal'), 'product_nc', ['raised_from_signal'], unique=False)
    op.create_index(op.f('ix_product_nc_status'), 'product_nc', ['status'], unique=False)
    op.create_table('product_return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rma_number', sa.String(length=40), nullable=False),
    sa.Column('date_raised', sa.Date(), nullable=True),
    sa.Column('organisation_as_written', sa.String(length=200), nullable=True),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('product', sa.String(length=40), nullable=True),
    sa.Column('serial_number_as_written', sa.String(length=60), nullable=True),
    sa.Column('hw_rev', sa.String(length=20), nullable=True),
    sa.Column('sw_version', sa.String(length=20), nullable=True),
    sa.Column('customer_reported_fault', sa.Text(), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.Column('technician_findings', sa.Text(), nullable=True),
    sa.Column('component_replaced', sa.String(length=120), nullable=True),
    sa.Column('linked_complaint', sa.String(length=40), nullable=True),
    sa.Column('disposition', sa.String(length=80), nullable=True),
    sa.Column('replacement_serial', sa.String(length=60), nullable=True),
    sa.Column('date_closed', sa.Date(), nullable=True),
    sa.Column('technician', sa.String(length=120), nullable=True),
    sa.Column('warranty_status', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('linked_signal', sa.String(length=40), nullable=True),
    sa.Column('resolved_customer_id', sa.String(length=32), nullable=True),
    sa.Column('resolved_hub_id', sa.String(length=32), nullable=True),
    sa.Column('resolved_event_code', sa.String(length=40), nullable=True),
    sa.Column('row_origin', sa.Enum('Human', 'Agent (accepted)', 'Agent (edited)', name='roworigin', native_enum=False), nullable=False),
    sa.Column('captured_from', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_return_captured_from'), 'product_return', ['captured_from'], unique=False)
    op.create_index(op.f('ix_product_return_customer_id'), 'product_return', ['customer_id'], unique=False)
    op.create_index(op.f('ix_product_return_date_raised'), 'product_return', ['date_raised'], unique=False)
    op.create_index(op.f('ix_product_return_linked_complaint'), 'product_return', ['linked_complaint'], unique=False)
    op.create_index(op.f('ix_product_return_linked_signal'), 'product_return', ['linked_signal'], unique=False)
    op.create_index(op.f('ix_product_return_resolved_customer_id'), 'product_return', ['resolved_customer_id'], unique=False)
    op.create_index(op.f('ix_product_return_resolved_event_code'), 'product_return', ['resolved_event_code'], unique=False)
    op.create_index(op.f('ix_product_return_resolved_hub_id'), 'product_return', ['resolved_hub_id'], unique=False)
    op.create_index(op.f('ix_product_return_rma_number'), 'product_return', ['rma_number'], unique=True)
    op.create_index(op.f('ix_product_return_row_origin'), 'product_return', ['row_origin'], unique=False)
    op.create_table('signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.String(length=40), nullable=False),
    sa.Column('raised', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('indicator_id', sa.String(length=16), nullable=False),
    sa.Column('product', sa.String(length=40), nullable=True),
    sa.Column('cohort', sa.Enum('all', 'sw_version', 'hw_revision', 'site', 'ward', 'lot', name='cohortkind', native_enum=False), nullable=False),
    sa.Column('cohort_value', sa.String(length=80), nullable=True),
    sa.Column('observed_rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('baseline', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('window_start', sa.Date(), nullable=True),
    sa.Column('window_end', sa.Date(), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=True),
    sa.Column('denominator_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('linked_events', sa.JSON(), nullable=True),
    sa.Column('capture_dependent', sa.Boolean(), nullable=True),
    sa.Column('agent_rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Open', 'Monitoring', 'Promoted', 'Closed - no action', name='signalstatus', native_enum=False), nullable=False),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('outcome_rationale', sa.Text(), nullable=True),
    sa.Column('linked_nc', sa.String(length=40), nullable=True),
    sa.Column('raised_at_pms_meeting', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_capture_dependent'), 'signal', ['capture_dependent'], unique=False)
    op.create_index(op.f('ix_signal_cohort'), 'signal', ['cohort'], unique=False)
    op.create_index(op.f('ix_signal_cohort_value'), 'signal', ['cohort_value'], unique=False)
    op.create_index(op.f('ix_signal_indicator_id'), 'signal', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_signal_linked_nc'), 'signal', ['linked_nc'], unique=False)
    op.create_index(op.f('ix_signal_signal_id'), 'signal', ['signal_id'], unique=True)
    op.create_index(op.f('ix_signal_status'), 'signal', ['status'], unique=False)
    op.create_table('source_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_snapshot_filename'), 'source_snapshot', ['filename'], unique=False)
    op.create_table('draft_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('proposed_value', sa.Text(), nullable=True),
    sa.Column('accepted_value', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['capture_draft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_field_draft_id'), 'draft_field', ['draft_id'], unique=False)
    op.create_table('hub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hub_id', sa.String(length=32), nullable=False),
    sa.Column('serial_number', sa.String(length=60), nullable=True),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('organisation_name_as_written', sa.String(length=200), nullable=True),
    sa.Column('ward_id', sa.String(length=40), nullable=True),
    sa.Column('bed_id', sa.String(length=40), nullable=True),
    sa.Column('hw_revision', sa.String(length=20), nullable=True),
    sa.Column('sw_version_last_observed', sa.String(length=20), nullable=True),
    sa.Column('sw_version_observed_on', sa.Date(), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('unit_status', sa.Enum('In service', 'Installed', 'At depot (RMA)', 'Decommissioned', 'Spare', 'Shipped - not installed', name='unitstatus', native_enum=False), nullable=True),
    sa.Column('pairing_id', sa.String(length=60), nullable=True),
    sa.Column('pairing_status', sa.String(length=40), nullable=True),
    sa.Column('last_online_local', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decommission_date', sa.Date(), nullable=True),
    sa.Column('depot_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_organisation.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hub_customer_id'), 'hub', ['customer_id'], unique=False)
    op.create_index(op.f('ix_hub_hub_id'), 'hub', ['hub_id'], unique=True)
    op.create_index(op.f('ix_hub_hw_revision'), 'hub', ['hw_revision'], unique=False)
    op.create_index(op.f('ix_hub_pairing_id'), 'hub', ['pairing_id'], unique=False)
    op.create_index(op.f('ix_hub_serial_number'), 'hub', ['serial_number'], unique=False)
    op.create_index(op.f('ix_hub_sw_version_last_observed'), 'hub', ['sw_version_last_observed'], unique=False)
    op.create_index(op.f('ix_hub_unit_status'), 'hub', ['unit_status'], unique=False)
    op.create_index(op.f('ix_hub_ward_id'), 'hub', ['ward_id'], unique=False)
    op.create_table('patch_lot_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_code', sa.String(length=40), nullable=False),
    sa.Column('product_code', sa.String(length=40), nullable=True),
    sa.Column('manufactured', sa.Date(), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('organisation_name_as_written', sa.String(length=200), nullable=True),
    sa.Column('patches_allocated', sa.Integer(), nullable=True),
    sa.Column('boxes', sa.Integer(), nullable=True),
    sa.Column('shipped_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_organisation.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patch_lot_allocation_customer_id'), 'patch_lot_allocation', ['customer_id'], unique=False)
    op.create_index(op.f('ix_patch_lot_allocation_lot_code'), 'patch_lot_allocation', ['lot_code'], unique=False)
    op.create_index(op.f('ix_patch_lot_allocation_shipped_date'), 'patch_lot_allocation', ['shipped_date'], unique=False)
    op.create_table('review_verdict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.Column('completion_id', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.Enum('Pending', 'Accepted', 'Edited', 'Rejected', name='draftstatus', native_enum=False), nullable=False),
    sa.Column('reviewed_by', sa.String(length=120), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('edited_fields', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['completion_id'], ['completion_suggestion.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['capture_draft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_verdict_completion_id'), 'review_verdict', ['completion_id'], unique=False)
    op.create_index(op.f('ix_review_verdict_draft_id'), 'review_verdict', ['draft_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_verdict_draft_id'), table_name='review_verdict')
    op.drop_index(op.f('ix_review_verdict_completion_id'), table_name='review_verdict')
    op.drop_table('review_verdict')
    op.drop_index(op.f('ix_patch_lot_allocation_shipped_date'), table_name='patch_lot_allocation')
    op.drop_index(op.f('ix_patch_lot_allocation_lot_code'), table_name='patch_lot_allocation')
    op.drop_index(op.f('ix_patch_lot_allocation_customer_id'), table_name='patch_lot_allocation')
    op.drop_table('patch_lot_allocation')
    op.drop_index(op.f('ix_hub_ward_id'), table_name='hub')
    op.drop_index(op.f('ix_hub_unit_status'), table_name='hub')
    op.drop_index(op.f('ix_hub_sw_version_last_observed'), table_name='hub')
    op.drop_index(op.f('ix_hub_serial_number'), table_name='hub')
    op.drop_index(op.f('ix_hub_pairing_id'), table_name='hub')
    op.drop_index(op.f('ix_hub_hw_revision'), table_name='hub')
    op.drop_index(op.f('ix_hub_hub_id'), table_name='hub')
    op.drop_index(op.f('ix_hub_customer_id'), table_name='hub')
    op.drop_table('hub')
    op.drop_index(op.f('ix_draft_field_draft_id'), table_name='draft_field')
    op.drop_table('draft_field')
    op.drop_index(op.f('ix_source_snapshot_filename'), table_name='source_snapshot')
    op.drop_table('source_snapshot')
    op.drop_index(op.f('ix_signal_status'), table_name='signal')
    op.drop_index(op.f('ix_signal_signal_id'), table_name='signal')
    op.drop_index(op.f('ix_signal_linked_nc'), table_name='signal')
    op.drop_index(op.f('ix_signal_indicator_id'), table_name='signal')
    op.drop_index(op.f('ix_signal_cohort_value'), table_name='signal')
    op.drop_index(op.f('ix_signal_cohort'), table_name='signal')
    op.drop_index(op.f('ix_signal_capture_dependent'), table_name='signal')
    op.drop_table('signal')
    op.drop_index(op.f('ix_product_return_row_origin'), table_name='product_return')
    op.drop_index(op.f('ix_product_return_rma_number'), table_name='product_return')
    op.drop_index(op.f('ix_product_return_resolved_hub_id'), table_name='product_return')
    op.drop_index(op.f('ix_product_return_resolved_event_code'), table_name='product_return')
    op.drop_index(op.f('ix_product_return_resolved_customer_id'), table_name='product_return')
    op.drop_index(op.f('ix_product_return_linked_signal'), table_name='product_return')
    op.drop_index(op.f('ix_product_return_linked_complaint'), table_name='product_return')
    op.drop_index(op.f('ix_product_return_date_raised'), table_name='product_return')
    op.drop_index(op.f('ix_product_return_customer_id'), table_name='product_return')
    op.drop_index(op.f('ix_product_return_captured_from'), table_name='product_return')
    op.drop_table('product_return')
    op.drop_index(op.f('ix_product_nc_status'), table_name='product_nc')
    op.drop_index(op.f('ix_product_nc_raised_from_signal'), table_name='product_nc')
    op.drop_index(op.f('ix_product_nc_nc_id'), table_name='product_nc')
    op.drop_index(op.f('ix_product_nc_linked_capa'), table_name='product_nc')
    op.drop_index(op.f('ix_product_nc_indicator_id'), table_name='product_nc')
    op.drop_index(op.f('ix_product_nc_date_raised'), table_name='product_nc')
    op.drop_table('product_nc')
    op.drop_index(op.f('ix_pms_review_meeting_meeting_id'), table_name='pms_review_meeting')
    op.drop_index(op.f('ix_pms_review_meeting_meeting_date'), table_name='pms_review_meeting')
    op.drop_table('pms_review_meeting')
    op.drop_index(op.f('ix_indicator_internal_code'), table_name='indicator')
    op.drop_index(op.f('ix_indicator_indicator_id'), table_name='indicator')
    op.drop_table('indicator')
    op.drop_index(op.f('ix_incident_ward_id'), table_name='incident')
    op.drop_index(op.f('ix_incident_sw_version_at_time'), table_name='incident')
    op.drop_index(op.f('ix_incident_row_origin'), table_name='incident')
    op.drop_index(op.f('ix_incident_resolved_hub_id'), table_name='incident')
    op.drop_index(op.f('ix_incident_resolved_customer_id'), table_name='incident')
    op.drop_index(op.f('ix_incident_reported_date'), table_name='incident')
    op.drop_index(op.f('ix_incident_pairing_id'), table_name='incident')
    op.drop_index(op.f('ix_incident_incident_id'), table_name='incident')
    op.drop_index(op.f('ix_incident_hub_id'), table_name='incident')
    op.drop_index(op.f('ix_incident_event_code'), table_name='incident')
    op.drop_index(op.f('ix_incident_captured_from'), table_name='incident')
    op.drop_table('incident')
    op.drop_index(op.f('ix_data_check_ward'), table_name='data_check')
    op.drop_index(op.f('ix_data_check_row_origin'), table_name='data_check')
    op.drop_index(op.f('ix_data_check_resolved_hub_id'), table_name='data_check')
    op.drop_index(op.f('ix_data_check_resolved_event_codes'), table_name='data_check')
    op.drop_index(op.f('ix_data_check_resolved_customer_id'), table_name='data_check')
    op.drop_index(op.f('ix_data_check_patch_lot'), table_name='data_check')
    op.drop_index(op.f('ix_data_check_check_id'), table_name='data_check')
    op.drop_index(op.f('ix_data_check_check_date'), table_name='data_check')
    op.drop_index(op.f('ix_data_check_captured_from'), table_name='data_check')
    op.drop_table('data_check')
    op.drop_index(op.f('ix_customer_organisation_customer_id'), table_name='customer_organisation')
    op.drop_table('customer_organisation')
    op.drop_index(op.f('ix_controlled_document_status'), table_name='controlled_document')
    op.drop_index(op.f('ix_controlled_document_document_id'), table_name='controlled_document')
    op.drop_table('controlled_document')
    op.drop_index(op.f('ix_completion_suggestion_target_row_key'), table_name='completion_suggestion')
    op.drop_index(op.f('ix_completion_suggestion_target_register'), table_name='completion_suggestion')
    op.drop_index(op.f('ix_completion_suggestion_status'), table_name='completion_suggestion')
    op.drop_index(op.f('ix_completion_suggestion_field_name'), table_name='completion_suggestion')
    op.drop_index(op.f('ix_completion_suggestion_bot'), table_name='completion_suggestion')
    op.drop_index(op.f('ix_completion_suggestion_artifact_ref'), table_name='completion_suggestion')
    op.drop_table('completion_suggestion')
    op.drop_index(op.f('ix_complaint_status'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_row_origin'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_linked_signal'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_linked_rma'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_linked_nc'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_linked_incident'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_linked_comm'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_indicator_id'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_event_code'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_date_received'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_customer_id'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_complaint_id'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_captured_from'), table_name='complaint')
    op.drop_table('complaint')
    op.drop_index(op.f('ix_communication_row_origin'), table_name='communication')
    op.drop_index(op.f('ix_communication_resolved_event_code'), table_name='communication')
    op.drop_index(op.f('ix_communication_resolved_customer_id'), table_name='communication')
    op.drop_index(op.f('ix_communication_date_of_initial_email'), table_name='communication')
    op.drop_index(op.f('ix_communication_comm_id'), table_name='communication')
    op.drop_index(op.f('ix_communication_channel'), table_name='communication')
    op.drop_index(op.f('ix_communication_captured_from'), table_name='communication')
    op.drop_table('communication')
    op.drop_index(op.f('ix_capture_draft_target_register'), table_name='capture_draft')
    op.drop_index(op.f('ix_capture_draft_status'), table_name='capture_draft')
    op.drop_index(op.f('ix_capture_draft_proposed_event_code'), table_name='capture_draft')
    op.drop_index(op.f('ix_capture_draft_bot'), table_name='capture_draft')
    op.drop_index(op.f('ix_capture_draft_artifact_ref'), table_name='capture_draft')
    op.drop_table('capture_draft')
    op.drop_index(op.f('ix_capa_status'), table_name='capa')
    op.drop_index(op.f('ix_capa_row_origin'), table_name='capa')
    op.drop_index(op.f('ix_capa_date_recommended'), table_name='capa')
    op.drop_index(op.f('ix_capa_captured_from'), table_name='capa')
    op.drop_index(op.f('ix_capa_capa_id'), table_name='capa')
    op.drop_table('capa')
    op.drop_index(op.f('ix_agent_action_workflow'), table_name='agent_action')
    op.drop_index(op.f('ix_agent_action_timestamp'), table_name='agent_action')
    op.drop_index(op.f('ix_agent_action_tier'), table_name='agent_action')
    op.drop_index(op.f('ix_agent_action_human_verdict'), table_name='agent_action')
    op.drop_index(op.f('ix_agent_action_action_id'), table_name='agent_action')
    op.drop_table('agent_action')
    # ### end Alembic commands ###
