"""email message id is not unique

Revision ID: aa17ec104d8d
Revises: c12135e1be6d
Create Date: 2026-09-13 21:15:19.038046
"""
from alembic import op
import sqlalchemy as sa


revision = 'aa17ec104d8d'
down_revision = 'c12135e1be6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_message', 'file_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_index(op.f('ix_email_message_message_id'), table_name='email_message')
    op.create_index(op.f('ix_email_message_message_id'), 'email_message', ['message_id'], unique=False)
    op.create_index(op.f('ix_email_message_file_path'), 'email_message', ['file_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_message_file_path'), table_name='email_message')
    op.drop_index(op.f('ix_email_message_message_id'), table_name='email_message')
    op.create_index(op.f('ix_email_message_message_id'), 'email_message', ['message_id'], unique=True)
    op.alter_column('email_message', 'file_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
