"""upstream source artifacts

Revision ID: c12135e1be6d
Revises: 48632b40bbe6
Create Date: 2026-09-13 21:11:50.191595
"""
from alembic import op
import sqlalchemy as sa


revision = 'c12135e1be6d'
down_revision = '48632b40bbe6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=200), nullable=False),
    sa.Column('mailbox', sa.String(length=40), nullable=True),
    sa.Column('file_path', sa.String(length=200), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('from_name', sa.String(length=200), nullable=True),
    sa.Column('from_email', sa.String(length=200), nullable=True),
    sa.Column('to_emails', sa.Text(), nullable=True),
    sa.Column('cc_emails', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('in_reply_to', sa.String(length=200), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_message_from_email'), 'email_message', ['from_email'], unique=False)
    op.create_index(op.f('ix_email_message_in_reply_to'), 'email_message', ['in_reply_to'], unique=False)
    op.create_index(op.f('ix_email_message_mailbox'), 'email_message', ['mailbox'], unique=False)
    op.create_index(op.f('ix_email_message_message_id'), 'email_message', ['message_id'], unique=True)
    op.create_index(op.f('ix_email_message_processed_at'), 'email_message', ['processed_at'], unique=False)
    op.create_index(op.f('ix_email_message_sent_at'), 'email_message', ['sent_at'], unique=False)
    op.create_table('meeting_transcript',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.String(length=40), nullable=False),
    sa.Column('comm_id', sa.String(length=40), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('meeting_date', sa.Date(), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('attendees', sa.JSON(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_transcript_comm_id'), 'meeting_transcript', ['comm_id'], unique=False)
    op.create_index(op.f('ix_meeting_transcript_meeting_date'), 'meeting_transcript', ['meeting_date'], unique=False)
    op.create_index(op.f('ix_meeting_transcript_processed_at'), 'meeting_transcript', ['processed_at'], unique=False)
    op.create_index(op.f('ix_meeting_transcript_transcript_id'), 'meeting_transcript', ['transcript_id'], unique=True)
    op.create_table('part_replaced',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.String(length=40), nullable=False),
    sa.Column('work_order_id', sa.String(length=40), nullable=True),
    sa.Column('part_number', sa.String(length=60), nullable=True),
    sa.Column('part_description', sa.Text(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_replaced_line_id'), 'part_replaced', ['line_id'], unique=True)
    op.create_index(op.f('ix_part_replaced_part_number'), 'part_replaced', ['part_number'], unique=False)
    op.create_index(op.f('ix_part_replaced_work_order_id'), 'part_replaced', ['work_order_id'], unique=False)
    op.create_table('technician_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.String(length=40), nullable=False),
    sa.Column('work_order_id', sa.String(length=40), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('technician', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technician_note_note_id'), 'technician_note', ['note_id'], unique=True)
    op.create_index(op.f('ix_technician_note_work_order_id'), 'technician_note', ['work_order_id'], unique=False)
    op.create_table('telemetry_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('hub_id', sa.String(length=32), nullable=True),
    sa.Column('serial', sa.String(length=60), nullable=True),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('ward_id', sa.String(length=40), nullable=True),
    sa.Column('bed_id', sa.String(length=40), nullable=True),
    sa.Column('ts_device', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ts_received', sa.DateTime(timezone=True), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('sw_version', sa.String(length=20), nullable=True),
    sa.Column('hw_revision', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_event_code'), 'telemetry_event', ['code'], unique=False)
    op.create_index(op.f('ix_telemetry_event_customer_id'), 'telemetry_event', ['customer_id'], unique=False)
    op.create_index(op.f('ix_telemetry_event_dedupe_key'), 'telemetry_event', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_telemetry_event_event_id'), 'telemetry_event', ['event_id'], unique=True)
    op.create_index(op.f('ix_telemetry_event_hub_id'), 'telemetry_event', ['hub_id'], unique=False)
    op.create_index(op.f('ix_telemetry_event_hw_revision'), 'telemetry_event', ['hw_revision'], unique=False)
    op.create_index(op.f('ix_telemetry_event_processed_at'), 'telemetry_event', ['processed_at'], unique=False)
    op.create_index(op.f('ix_telemetry_event_sw_version'), 'telemetry_event', ['sw_version'], unique=False)
    op.create_index(op.f('ix_telemetry_event_ts_device'), 'telemetry_event', ['ts_device'], unique=False)
    op.create_index(op.f('ix_telemetry_event_ts_received'), 'telemetry_event', ['ts_received'], unique=False)
    op.create_index(op.f('ix_telemetry_event_ward_id'), 'telemetry_event', ['ward_id'], unique=False)
    op.create_table('telemetry_heartbeat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('hub_id', sa.String(length=32), nullable=True),
    sa.Column('ts_device', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ts_received', sa.DateTime(timezone=True), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('sw_version', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_heartbeat_event_id'), 'telemetry_heartbeat', ['event_id'], unique=True)
    op.create_index(op.f('ix_telemetry_heartbeat_hub_id'), 'telemetry_heartbeat', ['hub_id'], unique=False)
    op.create_index(op.f('ix_telemetry_heartbeat_sw_version'), 'telemetry_heartbeat', ['sw_version'], unique=False)
    op.create_index(op.f('ix_telemetry_heartbeat_ts_device'), 'telemetry_heartbeat', ['ts_device'], unique=False)
    op.create_index(op.f('ix_telemetry_heartbeat_ts_received'), 'telemetry_heartbeat', ['ts_received'], unique=False)
    op.create_table('ward_round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.String(length=40), nullable=False),
    sa.Column('round_date', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('organisation_as_written', sa.String(length=200), nullable=True),
    sa.Column('ward_id', sa.String(length=40), nullable=True),
    sa.Column('walked_by', sa.String(length=120), nullable=True),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('beds_planned', sa.Integer(), nullable=True),
    sa.Column('beds_walked', sa.Integer(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('incomplete_reason', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ward_round_complete'), 'ward_round', ['complete'], unique=False)
    op.create_index(op.f('ix_ward_round_customer_id'), 'ward_round', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ward_round_processed_at'), 'ward_round', ['processed_at'], unique=False)
    op.create_index(op.f('ix_ward_round_round_date'), 'ward_round', ['round_date'], unique=False)
    op.create_index(op.f('ix_ward_round_round_id'), 'ward_round', ['round_id'], unique=True)
    op.create_index(op.f('ix_ward_round_ward_id'), 'ward_round', ['ward_id'], unique=False)
    op.create_table('work_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.String(length=40), nullable=False),
    sa.Column('rma_number', sa.String(length=40), nullable=True),
    sa.Column('raised_date', sa.Date(), nullable=True),
    sa.Column('serial_as_written', sa.String(length=60), nullable=True),
    sa.Column('organisation_as_written', sa.String(length=200), nullable=True),
    sa.Column('reported_fault_verbatim', sa.Text(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('technician', sa.String(length=120), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('disposition', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_processed_at'), 'work_order', ['processed_at'], unique=False)
    op.create_index(op.f('ix_work_order_raised_date'), 'work_order', ['raised_date'], unique=False)
    op.create_index(op.f('ix_work_order_rma_number'), 'work_order', ['rma_number'], unique=False)
    op.create_index(op.f('ix_work_order_work_order_id'), 'work_order', ['work_order_id'], unique=True)
    op.create_table('round_bed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.String(length=40), nullable=False),
    sa.Column('bed_id', sa.String(length=40), nullable=True),
    sa.Column('pairing_id', sa.String(length=60), nullable=True),
    sa.Column('serial_read', sa.String(length=60), nullable=True),
    sa.Column('patch_lot_read', sa.String(length=40), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('walked', sa.Boolean(), nullable=True),
    sa.Column('check_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['ward_round.round_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_round_bed_check_id'), 'round_bed', ['check_id'], unique=False)
    op.create_index(op.f('ix_round_bed_pairing_id'), 'round_bed', ['pairing_id'], unique=False)
    op.create_index(op.f('ix_round_bed_round_id'), 'round_bed', ['round_id'], unique=False)
    op.create_index(op.f('ix_round_bed_walked'), 'round_bed', ['walked'], unique=False)
    op.create_table('transcript_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.String(length=40), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('at', sa.String(length=12), nullable=True),
    sa.Column('speaker', sa.String(length=120), nullable=True),
    sa.Column('speaker_org', sa.String(length=120), nullable=True),
    sa.Column('speaker_role', sa.String(length=120), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['meeting_transcript.transcript_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_line_at'), 'transcript_line', ['at'], unique=False)
    op.create_index(op.f('ix_transcript_line_transcript_id'), 'transcript_line', ['transcript_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_line_transcript_id'), table_name='transcript_line')
    op.drop_index(op.f('ix_transcript_line_at'), table_name='transcript_line')
    op.drop_table('transcript_line')
    op.drop_index(op.f('ix_round_bed_walked'), table_name='round_bed')
    op.drop_index(op.f('ix_round_bed_round_id'), table_name='round_bed')
    op.drop_index(op.f('ix_round_bed_pairing_id'), table_name='round_bed')
    op.drop_index(op.f('ix_round_bed_check_id'), table_name='round_bed')
    op.drop_table('round_bed')
    op.drop_index(op.f('ix_work_order_work_order_id'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_rma_number'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_raised_date'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_processed_at'), table_name='work_order')
    op.drop_table('work_order')
    op.drop_index(op.f('ix_ward_round_ward_id'), table_name='ward_round')
    op.drop_index(op.f('ix_ward_round_round_id'), table_name='ward_round')
    op.drop_index(op.f('ix_ward_round_round_date'), table_name='ward_round')
    op.drop_index(op.f('ix_ward_round_processed_at'), table_name='ward_round')
    op.drop_index(op.f('ix_ward_round_customer_id'), table_name='ward_round')
    op.drop_index(op.f('ix_ward_round_complete'), table_name='ward_round')
    op.drop_table('ward_round')
    op.drop_index(op.f('ix_telemetry_heartbeat_ts_received'), table_name='telemetry_heartbeat')
    op.drop_index(op.f('ix_telemetry_heartbeat_ts_device'), table_name='telemetry_heartbeat')
    op.drop_index(op.f('ix_telemetry_heartbeat_sw_version'), table_name='telemetry_heartbeat')
    op.drop_index(op.f('ix_telemetry_heartbeat_hub_id'), table_name='telemetry_heartbeat')
    op.drop_index(op.f('ix_telemetry_heartbeat_event_id'), table_name='telemetry_heartbeat')
    op.drop_table('telemetry_heartbeat')
    op.drop_index(op.f('ix_telemetry_event_ward_id'), table_name='telemetry_event')
    op.drop_index(op.f('ix_telemetry_event_ts_received'), table_name='telemetry_event')
    op.drop_index(op.f('ix_telemetry_event_ts_device'), table_name='telemetry_event')
    op.drop_index(op.f('ix_telemetry_event_sw_version'), table_name='telemetry_event')
    op.drop_index(op.f('ix_telemetry_event_processed_at'), table_name='telemetry_event')
    op.drop_index(op.f('ix_telemetry_event_hw_revision'), table_name='telemetry_event')
    op.drop_index(op.f('ix_telemetry_event_hub_id'), table_name='telemetry_event')
    op.drop_index(op.f('ix_telemetry_event_event_id'), table_name='telemetry_event')
    op.drop_index(op.f('ix_telemetry_event_dedupe_key'), table_name='telemetry_event')
    op.drop_index(op.f('ix_telemetry_event_customer_id'), table_name='telemetry_event')
    op.drop_index(op.f('ix_telemetry_event_code'), table_name='telemetry_event')
    op.drop_table('telemetry_event')
    op.drop_index(op.f('ix_technician_note_work_order_id'), table_name='technician_note')
    op.drop_index(op.f('ix_technician_note_note_id'), table_name='technician_note')
    op.drop_table('technician_note')
    op.drop_index(op.f('ix_part_replaced_work_order_id'), table_name='part_replaced')
    op.drop_index(op.f('ix_part_replaced_part_number'), table_name='part_replaced')
    op.drop_index(op.f('ix_part_replaced_line_id'), table_name='part_replaced')
    op.drop_table('part_replaced')
    op.drop_index(op.f('ix_meeting_transcript_transcript_id'), table_name='meeting_transcript')
    op.drop_index(op.f('ix_meeting_transcript_processed_at'), table_name='meeting_transcript')
    op.drop_index(op.f('ix_meeting_transcript_meeting_date'), table_name='meeting_transcript')
    op.drop_index(op.f('ix_meeting_transcript_comm_id'), table_name='meeting_transcript')
    op.drop_table('meeting_transcript')
    op.drop_index(op.f('ix_email_message_sent_at'), table_name='email_message')
    op.drop_index(op.f('ix_email_message_processed_at'), table_name='email_message')
    op.drop_index(op.f('ix_email_message_message_id'), table_name='email_message')
    op.drop_index(op.f('ix_email_message_mailbox'), table_name='email_message')
    op.drop_index(op.f('ix_email_message_in_reply_to'), table_name='email_message')
    op.drop_index(op.f('ix_email_message_from_email'), table_name='email_message')
    op.drop_table('email_message')
    # ### end Alembic commands ###
